trigger:
- dt_extension

steps:
- task: pushEventTask@1
  inputs:
    eventType: 'deployment'
    dynatraceTenantUrl: '$(dynatraceTenantUrl)'
    dynatraceApiToken: '$(dynatraceApiToken)'
    tagRule: |
      [{
        "meTypes": "SERVICE",
        "tags": [{
           "context": "CONTEXTLESS",
           "key": "app",
           "value": "$(dt_app)"
        },
      {
           "context": "CONTEXTLESS",
           "key": "env",
           "value": "$(dt_env)"
        }]
      }]
    deploymentName: 'Deployment: Azure DevOps: $(Release.DefinitionName)'
    deploymentVersion: 'Azure DevOps Release: $(Release.ReleaseName)'
    remediationAction: 'ansible'
    source: 'DevOps Pipeline'

