trigger:
- dt_extension

steps:
- task: pushEventTask@1
  inputs:
    eventType: 'deployment'
    dynatraceTenantUrl: '$(dynatraceTenantUrl)'
    dynatraceApiToken: '$(dynatraceApiToken)'
    tagRule: |
      [{
        "meTypes": "SERVICE",
        "tags": [{
           "context": "CONTEXTLESS",
           "key": "app",
           "value": "$(dt_app)"
        },
      {
           "context": "CONTEXTLESS",
           "key": "environment",
           "value": "$(dt_env)"
        }]
      }]
    customProperties: |
      {
          "Deployment Start Time": "$(DeploymentEventStartTime)",
          "Deployment End Time": "$(DeploymentEventEndTime)",
          "Application": "$(Application)",
          "Application Owner": "$(ApplicationOwner)",
          "Release Reason": "$(Release.Reason)",
          "Release Requested For": "$(Release.RequestedFor)",
          "Release Description": "$(Release.ReleaseDescription)"
      }
    deploymentName: 'Deployment: Azure DevOps: $(Release.DefinitionName)'
    deploymentVersion: 'Azure DevOps Release: $(Release.ReleaseName)'
    remediationAction: 'ansible'
    source: 'DevOps Pipeline'

